const Menu = [
    {
        id: 1,
        image: "images/dosa.jpg",
        name: "Dosa",
        category: "Breakfast",
        price: "150.00",
        hotel: "Hotel SaiKripa",
        description: "Mashal Chowk, Daman - 396210",
    },
    {
        id: 2,
        image: "images/chole bhature.jpg",
        name: "Chole Bhature",
        category: "Lunch",
        price: "300.00",
        hotel: "The Kutty's",
        description: "Near Daman Bus Depot, Daman - 396210",
    },
    {
        id: 3,
        image: "images/biryani.jpg",
        name: "Veg Biryani",
        category: "Dinner",
        price: "350.00",
        hotel: "Hotel SaiKripa",
        description: "Mashal Chowk, Daman - 396210",
    },
    {
        id: 4,
        image: "images/poha.jpg",
        name: "Poha",
        category: "Breakfast",
        price: "90.00",
        hotel: "Hotel Blue Lagoon",
        description: "Devka Beach Road, Devka, Daman - 396210",
    },
    {
        id: 5,
        image: "images/paneer tikka.jpg",
        name: "Paneer Tikka",
        category: "Dinner",
        price: "450.00",
        hotel: "Hotel Blue Lagoon",
        description: "Devka Beach Road, Devka, Daman - 396210",
    },
    {
        id: 6,
        image: "images/parantha.jpg",
        name: "Parantha",
        category: "Lunch",
        price: "130.00",
        hotel: "Hotel SaiKripa",
        description: "Mashal Chowk, Daman - 396210",
    },
    {
        id: 7,
        image: "images/instant noodles.jpg",
        name: "Instant Noodles",
        category: "Breakfast",
        price: "90.00",
        hotel: "The Kutty's",
        description: "Near Daman Bus Depot, Daman - 396210",
    },
]
export default Menu;